name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable, "1.47.0"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v1

    - name: Set up Rust toolchain
      run: |
        rustup default ${{ matrix.rust_version }}
        rustup component add clippy rustfmt

    - name: Build and test (default features)
      run: |
        cargo build --verbose
        cargo test --verbose

    - name: Rustfmt and Clippy
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings
      if: matrix.rust_version == 'stable'
